name = "Euler"
uuid = "b03b4a57-29ac-4011-973d-4ed1b2b67fc4"
version = "0.1.0"
authors = ["Brinkhuis"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
BenchmarkTools = "1.6.3"
Combinatorics = "1.1.0"
DelimitedFiles = "1.9.1"
IJulia = "1.34.3"
Primes = "0.5.7"
